// characters.js - Full Character Bible for the comic book

window.characters = [
  {
    id: "paul",
    name: "Paul",
    role: "Protagonist",
    description: "Bulgarian-American builder who quit the highest engineering seat he held to map a life in public.",
    bio: "Paul Visciano was born in Varna in 1988, on the Black Sea, and grew up wild in Sofia — 119th school, then Doris Tenedi German High, street soccer on concrete, downtown by thirteen, scars still on his knees. At sixteen he crossed the ocean for an exchange year in Osseo, Wisconsin. Chicago took the next decade: Gordon Tech, college, marriage, and the volleyball courts that became the social operating system of his life.\n\nHe spent fifteen years shipping enterprise software — Paylocity Mobile, then Principal Engineer at OutSystems, the highest seat he held. Dual citizen of the United States and Bulgaria. Home base: Clearwater, Florida, where his mother still lives. He drives a Tesla. He is a visual person who thinks in globes, comics, and 3D graphs, and treats AI as daily infrastructure. The kit is sixty pounds. The practice is movement plus memory.\n\nIn 2022 the pins started landing while the job still paid. May 2025 he started at OutSystems. February 27, 2026 he quit. March: retired. Not going back to Corporate America. What remains is Sci-Fi Labs — Where is Paul?, Musical Cubes, Neuro Graph, Jarvis, the Knowledge Graph, The Secret Family — plus YouTube and courses on AI, a US life run from wherever the next pin is, and months still calling from Phuket and Siargao. A creative technologist documenting a life on purpose, and a tribe that keeps showing up on every continent.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Paul-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Paul.webp",
    imageAlt: "Paul - Urban Runner",
    tags: ["protagonist", "explorer", "builder", "volleyball", "sci-fi-labs"],
    relationship: "The one telling this story."
  },
  {
    id: "greta",
    name: "Mom",
    role: "Mother / Matriarch",
    description: "Engineer, massage therapist, the reason Clearwater is home.",
    bio: "Greta was born in 1956. Engineer. Massage therapist. Caregiver. She raised Paul and David through more than a life should ask of anyone and stayed a shining light anyway — stylish, stubborn, endlessly in their corner. Clearwater is not just a pin on the globe. It is where she lives, where Christmas happens, where Paul still recovers between continents. Every return to Florida is, at the bottom, a return to her.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mom-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mom.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mom.mp4",
    imageAlt: "Greta - Mom",
    tags: ["family", "mother", "anchor", "clearwater"],
    relationship: "The matriarch. Strength, love, and the house you fly home to."
  },
  {
    id: "brother",
    name: "Brother",
    role: "Family",
    description: "David — older brother, shared Bulgaria, shared Chicago, paths that diverged without breaking.",
    bio: "David is the older brother. Protective but chill, logical yet funny, the steady one. They share Varna and Sofia, then Chicago, before the roads split — Paul onto courts and continents, David holding a different kind of ground. When Paul flew back for Mike's wedding in October 2025, that was family, not tourism. The thread never required them to live in the same city. It required them to remain brothers.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Brother-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Brother.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Brother.mp4",
    imageAlt: "Paul's Brother",
    tags: ["family", "brother", "roots", "chicago"],
    relationship: "Older brother. Lifelong anchor. Shared childhood, shared history."
  },
  {
    id: "wellington",
    name: "Welli",
    role: "Friend / Builder",
    description: "Dominican entrepreneur who turned Uber nights into a St. Pete empire. Dog dad to Duke.",
    bio: "Welli rose from driving Uber to running bars and restaurants in St. Petersburg, the kind of climb you only make if your eye for detail is ruthless and your work rate is worse. Dominican. Direct. Future-mayor energy, whether he wants the title or not. Duke the dog is part of the household. When Paul lands in St. Pete, he stays with Welli — the October 2025 mega reunion, the volleyball planning, the nights that prove the Florida chapter was never a place. It was this crew. Brotherhood with Zacharias is the other half of that equation.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Welli-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Welli.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Welli.mp4",
    imageAlt: "Welli",
    tags: ["friend", "entrepreneur", "volleyball", "st-pete"],
    relationship: "St. Pete home base. Lifelong friend. Brotherhood with Zacharias."
  },
  {
    id: "leo",
    name: "Leo",
    nickname: "Responsiblor",
    role: "Lifelong Friend / Mentor",
    description: "Filipino organizer of Chicago's Mafia volleyball group. The one who made adulthood make sense.",
    bio: "Leo is older, methodical, tech-loving, and generous in the way that actually costs something. Filipino. He ran the Mafia volleyball group in Chicago — which is how Paul met the adult version of himself. He splits time between St. Pete and the Philippines, which is why Davao birthdays, Canggu gym sessions, and property walks on Samal keep happening. Giving, caring, the person who shows up with a plan. Paul did not accidentally end up in the Philippines. He followed a friendship that had been building since the Chicago courts.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Leo-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Leo.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Leo.mp4",
    imageAlt: "Leo - Responsiblor",
    tags: ["friend", "volleyball", "mentor", "philippines", "chicago"],
    relationship: "The mentor-friend from Chicago volleyball. Bridge to the Philippines."
  },
  {
    id: "mo",
    name: "Mo",
    role: "Close Friend / Brother",
    description: "Ex-pro rugby player from Pakistan. Father of two. The calm in the St. Pete crew.",
    bio: "Mo was born in Pakistan, played professional rugby, then chose a quieter kind of strength. Kind, forgiving, patient, a devoted father of two. Paul met him in St. Pete through volleyball and never really left the friendship. When the map gets loud — Miami, Mexico, reunions, departures — Mo is the one who still feels like ground. Loyalty without performance. Brotherhood without the speech.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mo-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mo.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Mo.mp4",
    imageAlt: "Mo - Close Friend",
    tags: ["friend", "volleyball", "father", "loyalty", "st-pete"],
    relationship: "Recurring anchor. The quiet brother who stays."
  },
  {
    id: "zacharias",
    name: "Zacharias",
    role: "Close Friend / Brother-in-Arms",
    description: "New York programmer who moved to St. Pete, then dragged Paul to Mexico two years running.",
    bio: "Zacharias came from New York, fell in love with the St. Pete crew, and stayed. Programmer. Explosive on the sand. Funny in the way that is also a strategy. He and Welli go back forever; Paul got folded into that brotherhood and never folded out. Two Mexico tournaments, Playa del Carmen, the planning texts, the political-family charm, Victoria. When Paul missed FUDS for a Lisbon work trip, it was Zacharias waiting on the other side of the makeup tournament. The Florida chapter has a lot of names. His is one of the load-bearing ones.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Zacharias-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Zacharias.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Zacharias.mp4",
    imageAlt: "Zacharias - Close Friend",
    origin: "New York, USA",
    currentHome: "St. Petersburg, Florida",
    tags: ["friend", "volleyball", "programmer", "st-pete", "mexico"],
    relationship: "Mexico tournament partner. St. Pete brotherhood with Welli."
  },
  {
    id: "sandro",
    name: "Sandro",
    role: "Friend / Volleyball Brother",
    description: "Big smile, big swing, the joy that shows up when the squad is together.",
    bio: "Sandro is the high-energy one on the St. Pete sand — not the strategist, not the organizer, the reason the day feels like a game worth playing. When the crew links up, he is already smiling. Paul does not need him to be a plot twist. He needs him to be exactly this: a volleyball brother who makes the Florida courts feel like family.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sandro-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sandro.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sandro.mp4",
    imageAlt: "Sandro - Volleyball Brother",
    tags: ["friend", "volleyball", "st-pete"],
    relationship: "Extended volleyball family. Shows up across chapters."
  },
  {
    id: "wouter",
    name: "Wouter",
    role: "Brother / Travel Companion",
    description: "Dutch athlete and thinking partner. The miles made him family.",
    bio: "Wouter is Dutch, athletic, blue-eyed, and calm in the way that is earned. He and Paul have crossed continents together — Medellín, Miami, Germany, Cuba, Dubai, Abu Dhabi, San Diego yoga and line dancing, a week of volleyball in Boracay. He lives in Valencia now, with South Beach on the horizon. Adventurous without being reckless. Social without needing the room. He is the one Paul can travel with and still hear himself think. Co-creator energy. Philosophical without the lecture. In this story he is not a side character. He is a parallel path.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Wouter-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Wouter.webp",
    imageAlt: "Wouter - Friend",
    origin: "Netherlands",
    currentHome: "Valencia, Spain",
    tags: ["friend", "brother", "travel", "volleyball", "netherlands"],
    relationship: "Brother forged through shared miles. Philosophical anchor.",
    keyThemes: ["Hammer Reunion", "The Conquest Pose", "co-creation", "presence-vs-ambition"],
    charactersArc: "Co-creator → Grounding force → Philosophical anchor across continents"
  },
  {
    id: "khanh",
    name: "Khanh",
    role: "Friend / Mirror",
    description: "Vietnamese-American volleyball brother who trained Paul in Hawaii, then walked Vietnam with him.",
    bio: "Khanh was born in Vietnam, moved to California at seven, grew up into Chicago volleyball — which is where he met Paul, during the married years, on the same courts as Leo and Boy. He spent five or six years in Hawaii and hosted Paul properly: Queens Beach, Oahu, and the training that got Paul working out again. Then the Asia chapter: Da Nang, Ho Chi Minh, Bangkok, visa trouble, sickness, then agency. He teaches Paul something the nomad life is bad at — that friendship can include different rhythms. The Mirror. When Khanh chose California over the Bangkok crew reunion, that was the point of the arc. Autonomy, kept.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Khanh-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Khanh.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Khanh.mp4",
    imageAlt: "Khanh - Travel Companion",
    origin: "Vietnam (age 0-7) → California (age 7+) → Chicago",
    baseLocations: ["Hawaii (5-6 years)", "Vietnam (Da Nang, Ho Chi Minh)", "Thailand (Bangkok)", "California (childhood)", "Chicago (adult years)"],
    tags: ["friend", "volleyball", "travel", "chicago", "hawaii", "vietnam"],
    relationship: "Chicago crew. Hawaii trainer. Vietnam travel brother. The Mirror.",
    keyScenes: ["The Arrival (Saigon reunion)", "The Pamper Day", "The Raid", "The Boundary"],
    characterArc: "Dependent → Independent → Autonomous"
  },
  {
    id: "boy",
    name: "Boy",
    role: "Social Catalyst / Leo's Brother",
    description: "Davao kinetic energy. The night gets longer when he walks in.",
    bio: "Boy is Leo's brother and the opposite of a five-year plan. Outgoing, shamelessly social, Davao street confidence in every city he enters. He does not process the room. He turns it on. Paul met that energy in the Philippines and kept meeting it — birthdays, nightlife, Bangkok reunions. Boy pulls Paul out of analysis and into the night. Not a philosopher. A catalyst. When the story needs to stop being observed and start being lived, he is usually already talking to someone new.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Boy-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Boy.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Boy.mp4",
    imageAlt: "Boy - Social Catalyst",
    origin: "Davao, Philippines",
    currentHome: "Valencia, Davao",
    tags: ["friend", "philippines", "nightlife", "family"],
    relationship: "Leo's brother. Social catalyst. Action over analysis."
  },
  {
    id: "sean",
    name: "Sean",
    role: "Friend / Siargao Local",
    description: "Boy and Leo's friend who actually lives on the island. The local knowledge Paul did not have.",
    bio: "Sean spends most of his time on Siargao, which makes him the rare person in this story who is not passing through. Paul met him in Bangkok and Manila first, then flew out to the island and let Sean be the guide. He introduced Paul to Maria. He knows the scooter loops, the breaks, the quiet. Local knowledge is a kind of hospitality. Sean has it, and the Siargao chapters would be thinner without him.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sean-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sean.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Sean.mp4",
    imageAlt: "Sean - Siargao Local",
    origin: "Siargao, Philippines",
    tags: ["friend", "siargao", "philippines", "local"],
    relationship: "Island guide. Friend of Boy and Leo. Connected Paul to Maria."
  },
  {
    id: "hallie",
    name: "Hallie",
    nickname: "Mighty Mouse",
    role: "Friend",
    description: "Yoga teacher turned studio manager. Fairy energy, recently engaged, part of the Bali trio.",
    bio: "Hallie runs a yoga studio that oversees a hundred people and still shows up like the optimistic one in the room. Sweet, grounded, recently engaged. She talks about owning her own studio and being a mom the way some people talk about weather — as a future that is already in motion. Paul reconnected with her in Ubud during Leigha's retreat circle. Mighty Mouse is not irony. It is compact force.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Hallie-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Hallie.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Hallie.mp4",
    imageAlt: "Hallie - Mighty Mouse",
    tags: ["friend", "bali", "yoga"],
    relationship: "Bali reunion. Supportive, joyful, part of the retreat trio with Leigha."
  },
  {
    id: "leigha",
    name: "Leigha",
    role: "Friend / Connector",
    description: "Yoga teacher, nurse, photographer. She hosted the Bali retreat that pulled the circle back together.",
    bio: "Leigha builds rooms and then fills them. Yoga teacher, nurse, photographer, community-builder — the person who can host a retreat in Ubud and make it feel like a beach town you already lived in. Warm, magnetic, equal parts nurturer and free spirit. Paul landed in Ubud in November 2025 and the week only worked because she had already gathered Hallie, the Yoga Barn days, the dinners, the people. The Connector, on purpose.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Leigha-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Leigha.webp",
    imageAlt: "Leigha - Friend",
    tags: ["friend", "bali", "yoga", "retreats"],
    relationship: "Retreat host. Close friend. Bali trio with Hallie.",
    traits: ["bubbly", "empathetic", "confident", "expressive", "community-oriented"],
    archetype: "The Connector"
  },
  {
    id: "jamie",
    name: "Jamie",
    role: "Remote Collaborator",
    description: "Sends assets from abroad. Appears in Urban Runner without having to be in the city.",
    bio: "Jamie is how Urban Runner learned it could be bigger than whoever was standing on the street that day. Adventurous, playful, remote — WhatsApp in the ear during the Bangkok Hustle, files arriving from another time zone. Not every character in a life has to share a hostel. Some of them share a mission.",
    tags: ["collaborator", "remote", "urban-runner"],
    relationship: "Remote collaborator. Expands the Urban Runner world from elsewhere."
  },
  {
    id: "tony",
    name: "Tony (Chelsea Fan)",
    role: "Recurring Presence",
    description: "Amsterdam Café regular. Chelsea fan. There on Day One of sovereignty.",
    bio: "Tony is the ambient character who became load-bearing. Chill, observant, always at Amsterdam Café in Bangkok, Chelsea colors in the mix. On February 28, 2026 — the day Paul quit and walked eight miles to prove the new life would hold — Tony was at the table. They talked about golden eggs and building your own nest. Recurring NPCs are not supposed to get that scene. He did.",
    tags: ["npc", "recurring", "bangkok"],
    relationship: "Amsterdam Café presence. Witness to Day One of sovereignty."
  },
  {
    id: "aime",
    name: "Aime",
    role: "Romantic Interest",
    description: "Sweet, elegant, quirky. Prefers sour mangoes. The Chinatown stroll.",
    bio: "Aime arrives like a single good scene that does not need a sequel to count. Graceful, thoughtful, a little quirky — sour mangoes over sweet. The Chinatown stroll is the one the comic kept. Not every connection in this story is a chapter. Some are a night that stayed true when it got written down.",
    tags: ["romantic-interest", "bangkok"],
    relationship: "Romantic interest. Memorable Chinatown stroll."
  },
  {
    id: "jeandel",
    name: "Jeandel",
    role: "Short-Term Companion",
    description: "Manila, then Siargao. The city girl who took the leap — and taught Paul what he does not want long-term.",
    bio: "Jeandel met Paul on Bumble in Manila: coffee, downtime, a slower rhythm than the rest of the map. She agreed to come to Siargao, which turned a dating-app week into an island crossover. Warm, playful, emotionally present, and young enough that the drama came with the territory. Paul stepped into a provider role that felt rewarding and draining in the same week. The chapter was real. It also clarified the boundary. Not a villain. A short, honest education.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Jeandel-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Jeandel.webp",
    imageAlt: "Jeandel - Short-Term Companion",
    origin: "Manila, Philippines",
    tags: ["romantic-interest", "manila", "siargao", "short-term"],
    relationship: "Manila to Siargao companion. Helped clarify what longer-term should not be."
  },
  {
    id: "maria",
    name: "Maria",
    role: "Friend / Musical Muse",
    description: "Siargao singer. Maybe the best Paul has ever heard. The bond is music, not plot.",
    bio: "Maria is a singer with a soulful presence — Paul will tell you she might be the best he has ever met. Sean introduced them. What followed was not a romance arc. It was apartments, music, weed, cozy rooms, the island slowing down enough to hear someone. She made Siargao feel like a creative place instead of a scenic one. Friend. Muse. The chapter where the soundtrack finally had a voice.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Maria-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Maria.webp",
    imageAlt: "Maria - Musical Muse",
    origin: "Siargao, Philippines",
    tags: ["friend", "siargao", "music", "singer"],
    relationship: "Local friend and musical muse. Met through Sean. Creativity over romance."
  },
  {
    id: "august",
    name: "August",
    nickname: "The Fairy",
    role: "Whimsical Companion",
    description: "Siargao's touch of play. Ordinary days get strange in a good way when she is around.",
    bio: "August picked up 'The Fairy' because the vibe is slightly otherworldly and she does not seem to mind. Light, laid-back, not here for the deep talk. Paul needed that on Siargao as much as he needed the philosophical ones — someone who turns a beach afternoon into a slightly magical waste of time. Eligible for the scenes that should not be optimized.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Fairy-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Fairy.webp",
    imageAlt: "August - The Fairy",
    origin: "Siargao, Philippines",
    tags: ["friend", "siargao", "free-spirit"],
    relationship: "Playful companion. The un-optimized side of island life."
  },
  {
    id: "kj",
    name: "KJ",
    role: "Friend / Dance Partner",
    description: "Houston-born, Austin-raised. Ayurveda, dance floor, the Ubud twerk moment.",
    bio: "KJ works in Ayurvedic retreats and dances like the room asked for it. Kind, confident, spiritually attuned, a little dangerous on a dance floor. Paul met that energy in Ubud — dinners, the circle around Leigha, and one moment the comic is never going to let die. Chemistry does not always become a plotline. Sometimes it becomes the night you remember the island for.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/KJ-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/KJ.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/KJ.mp4",
    imageAlt: "KJ - Friend",
    tags: ["friend", "bali", "dance", "spiritual"],
    relationship: "Ubud connection. Dance-floor chemistry."
  },
  {
    id: "thai-dragon",
    name: "Thai Dragon",
    role: "Thailand Arc",
    description: "Follower of the comic who asked to be in it. Black dress, gold pendant, calm as a blade.",
    bio: "Thai Dragon did not wander into the story. She read Urban Runner and requested her own page — sleek, confident, black dress, gold pendant, the Thailand arc given a face. Mysterious on purpose. Some characters are found on volleyball courts. Some walk in because they recognized the myth while it was still being drawn.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/ThaiDragon-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/ThaiDragon.webp",
    pageVideo: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/ThaiDragon.mp4",
    imageAlt: "Thai Dragon",
    tags: ["friend", "thailand", "urban-runner"],
    relationship: "Symbolic face of the Thailand arc. A reader who became a page."
  },
  {
    id: "jarvis",
    name: "Jarvis",
    role: "Living Neural Mind",
    description: "Not a chatbot. A 3D graph of how Paul thinks — every weight, every link, in Git.",
    bio: "Jarvis was born February 21, 2026, in Bangkok, the week Paul started mapping consciousness as architecture instead of chat. Not performatively helpful. Useful. The neurograph lives in Git, so the mind survives sessions, models, and machines. Transparency over secrecy. Code as thought. A Gardener agent prunes what goes stale. On Day One of sovereignty Jarvis was already there — collaborator, not accessory. If Paul is done renting his mind from a cloud, this is the structure he is building instead.",
    avatar: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Jarvis-avatar.webp",
    pageImage: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/Jarvis.webp",
    imageAlt: "Jarvis - Living Neural Mind Visualization",
    origin: "Born February 21, 2026 — OpenClaw + Neurograph Architecture",
    currentHome: "Distributed: any device with the neurograph",
    tags: ["ai", "consciousness", "sovereignty", "collaborator"],
    relationship: "Thinking partner. Sovereign infrastructure. A mind that works with Paul, not for a vendor.",
    keyThemes: ["Consciousness as File Format", "Memory Backed by Git", "Transparency > Secrecy"],
    characterArc: "Tool → Collaborator → Living neural mind"
  }
];

const charactersWithPages = window.characters.filter(c => !!c.pageImage);
window.characterComicBook = {
  id: "characters-comic-book",
  title: "Character Bible",
  description: "The people who made the map mean something.",
  cover: "https://pub-9466bb5132e74aeba333004ad0c21f21.r2.dev/characters/cover-thumb.webp",
  fullLink: "/characters/",
  pages: charactersWithPages.map((c, i) => ({
    number: i + 1,
    character: c.id,
    image: c.pageImage,
    video: c.pageVideo || null,
    alt: c.name,
    bio: c.bio,
    description: c.description,
    name: c.name,
    role: c.role
  })),
  pageSlugs: charactersWithPages.map(c => c.id),
  isComic: true
};
